### ISSUE TITLE
Improve the local database

### ISSUE THREAD

**Issue by JackMcGill** [JackMcKill/CP3407-Project#15]
Exactly what the title says. Currently, the local database that was implemented in #5 is a little bit overcomplicated for what we need. The code is all from a tutorial, and needs major refactoring before it can be used properly in our app.  Completing this issue should re-implement the local database, in a simpler way that is ready to be used with the rest of our app straight out of the box.

### Tasks

- [x] Remove old database code
- [x] Solve #10 so that `WeatherReportModel` objects can be passed between activities
- [x] Develop new local database 
- [x] Code to write to database
- [x] Code to read from database
- [x] Update documentation
