### ISSUE TITLE
Finalise local database code

### ISSUE THREAD

**Issue by JackMcGill** [JackMcKill/CP3407-Project#33]
# Overview
The local database currently works, but is still in a prototype phase. Completing this issue will mean that the database is fully operational and ready to be used

## TODO
- [x] Refactor so that instead of saving ID number that is provided to use from metaweather, a new ID number is saved. 
Why do this? Because the provided ID number is pointless to us. The ID numbers are not consecutive when viewing entries and therefore they are displayed out of order in the recyclerView by default. To fix this we should create a brand new ID number for each new entry, that increases for each consecutive entry to keep the database ordered correctly
- [x] Once the ID numbers have been sorted out, the database now needs to save ALL the properties for each weather report (except the provided ID). Currently it is only saving the ID number (for prototyping purposes)
- [x] `SingleWeatherReportActivity` needs to be modified so that it can display entries from the database
- [x] Some form of **delete** functionality
- [x] Some form of **update** functionality (to be used if an update weather report is received for a day that has already been added to the database) - *after reviewing our app requirements, and the limitations of metaweather, this is probably not needed (as a feature of our app is the short term archival of weather forecasts - we probably want to keep all old reports rather than update with the current weather updates)*
- [x] Instead of displaying the ID number on the `recyclerView`, something more useful to the user should be displayed, such as the location name + date
- [x] Ensure documentation is up to date
